'''
This script reads the .txt file generated by Jes√∫s Lopez's code extracting and
representing energy data
'''

import matplotlib.pyplot as plt


file_path = "/Users/jaimemorandominguez/Desktop/TFG/Pruebas_GLM/Salida/GLM_output_data.txt"

# Reading the .txt file and writing it in variables
file = open(file_path,"r")
lines = file.readlines()
length = len(lines)

t = [0] * len(lines)
lat_event = [0] * len(lines)
lon_event = [0] * len(lines)
event_integral = [0] * len(lines)
lat_flash = [0] * len(lines)
lon_flash = [0] * len(lines)
radiance = [0] * len(lines)

for i in range(len(lines)):
    for j in range(12):
        t[i] = str(t[i]) + lines[i][j]
    for count_lat_event in range(13,21,1):
        lat_event[i] = str(lat_event[i]) + lines[i][count_lat_event]
    for count_lon_event in range(23,32,1):
        lon_event[i] = str(lon_event[i]) + lines[i][count_lon_event]
    for count_lat_flash in range(39,47,1):
        lat_flash[i] = str(lat_flash[i]) + lines[i][count_lat_flash]
    for count_lon_flash in range(49,58,1):
        lon_flash[i] = str(lon_flash[i]) + lines[i][count_lon_flash]
    for count_rad in range(59,70,1):
        radiance[i] = str(radiance[i]) + lines[i][count_rad]
    
    t[i] = float(t[i])
    lat_event[i] = float(lat_event[i])
    lon_event[i] = -float(lon_event[i])     # CAUTION with the sign change
    lat_flash[i] = float(lat_flash[i])
    lon_flash[i] = -float(lon_flash[i])     # CAUTION with the sign change
    radiance[i] = float(radiance[i])
    
    file.close()


########### REPRESENTATIONS ###########

# Integrated event grid and flash representation
plt.figure()
plt.scatter(lon_event,lat_event)
plt.scatter(lon_flash,lat_flash,marker='x')
plt.axis('equal')
plt.title("Event grid")
plt.xlabel('Longitude [∫]')
plt.ylabel('Latitude [∫]')

# Radiance vs time graph representation
plt.figure()
plt.plot(t, radiance)
plt.title("Radiance VS Time")
plt.xlabel('Time (second of the day) [s]')
plt.ylabel('Radiance [J]')